//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probaraz
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Клиенты CustomAttributes)

    // *** End programmer edit section *** (Клиенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "НаимЗаказ as \'Заказчик\'",
            "Телефон as \'Телефон\'",
            "АдресПоставки as \'Адрес поставки\'",
            "РасчетСчет as \'Расчетный счет\'"})]
    [View("КлиентыL", new string[] {
            "НаимЗаказ as \'Заказчик\'",
            "Телефон as \'Телефон\'",
            "АдресПоставки as \'Адрес поставки\'",
            "РасчетСчет as \'Расчетный счет\'"})]
    public class Клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаимЗаказ;
        
        private int fТелефон;
        
        private string fАдресПоставки;
        
        private int fРасчетСчет;
        
        // *** Start programmer edit section *** (Клиенты CustomMembers)

        // *** End programmer edit section *** (Клиенты CustomMembers)

        
        /// <summary>
        /// АдресПоставки.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.АдресПоставки CustomAttributes)

        // *** End programmer edit section *** (Клиенты.АдресПоставки CustomAttributes)
        [StrLen(255)]
        public virtual string АдресПоставки
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.АдресПоставки Get start)

                // *** End programmer edit section *** (Клиенты.АдресПоставки Get start)
                string result = this.fАдресПоставки;
                // *** Start programmer edit section *** (Клиенты.АдресПоставки Get end)

                // *** End programmer edit section *** (Клиенты.АдресПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.АдресПоставки Set start)

                // *** End programmer edit section *** (Клиенты.АдресПоставки Set start)
                this.fАдресПоставки = value;
                // *** Start programmer edit section *** (Клиенты.АдресПоставки Set end)

                // *** End programmer edit section *** (Клиенты.АдресПоставки Set end)
            }
        }
        
        /// <summary>
        /// НаимЗаказ.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.НаимЗаказ CustomAttributes)

        // *** End programmer edit section *** (Клиенты.НаимЗаказ CustomAttributes)
        [StrLen(255)]
        public virtual string НаимЗаказ
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.НаимЗаказ Get start)

                // *** End programmer edit section *** (Клиенты.НаимЗаказ Get start)
                string result = this.fНаимЗаказ;
                // *** Start programmer edit section *** (Клиенты.НаимЗаказ Get end)

                // *** End programmer edit section *** (Клиенты.НаимЗаказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.НаимЗаказ Set start)

                // *** End programmer edit section *** (Клиенты.НаимЗаказ Set start)
                this.fНаимЗаказ = value;
                // *** Start programmer edit section *** (Клиенты.НаимЗаказ Set end)

                // *** End programmer edit section *** (Клиенты.НаимЗаказ Set end)
            }
        }
        
        /// <summary>
        /// РасчетСчет.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.РасчетСчет CustomAttributes)

        // *** End programmer edit section *** (Клиенты.РасчетСчет CustomAttributes)
        public virtual int РасчетСчет
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.РасчетСчет Get start)

                // *** End programmer edit section *** (Клиенты.РасчетСчет Get start)
                int result = this.fРасчетСчет;
                // *** Start programmer edit section *** (Клиенты.РасчетСчет Get end)

                // *** End programmer edit section *** (Клиенты.РасчетСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.РасчетСчет Set start)

                // *** End programmer edit section *** (Клиенты.РасчетСчет Set start)
                this.fРасчетСчет = value;
                // *** Start programmer edit section *** (Клиенты.РасчетСчет Set end)

                // *** End programmer edit section *** (Клиенты.РасчетСчет Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Телефон CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Get start)

                // *** End programmer edit section *** (Клиенты.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Клиенты.Телефон Get end)

                // *** End programmer edit section *** (Клиенты.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Set start)

                // *** End programmer edit section *** (Клиенты.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Клиенты.Телефон Set end)

                // *** End programmer edit section *** (Клиенты.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Probaraz.Клиенты));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Probaraz.Клиенты));
                }
            }
        }
    }
}
